import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import Providers from "@/components/providers";
import Navbar from "@/components/templates/navbar";
import Footer from "@/components/templates/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-[100vh] w-full`}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
          <Toaster
            position="bottom-right"
            toastOptions={{
              duration: 2500,
              style: {
                background: "transparent",
                border: "none",
                boxShadow: "none",
                marginRight: "3rem",
                paddingLeft: "1rem",
              },
            }}
          />
        </Providers>
      </body>
    </html>
  );
}
